version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    depends_on:
      - redis
    ports:
      - "8080:80"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"

  slave:
    image: "ghcr.io/mikedevresse/md5-cracker-slave:main"
    deploy:
      replicas: 0
    depends_on:
      - go

  redis:
    image: redis:6.2-alpine