version: "3.7"

services:
  go:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "8080:80"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"

  slave:
    image: itytophile/hash-slave
    command: ws://go/ws
    deploy:
      replicas: 0
    depends_on:
      - go