name: React build & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install
      run: |
        cd frontend
        yarn install

    - name: Build
      run: |
        cd frontend
        yarn build
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install
      run: |
        cd frontend
        yarn install

    - name: Test
      run: |
        cd frontend
        yarn test -- --watchAll=false
