name: React build & tests

env:
  working-directory: ./frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: ${{env.working-directory}}/yarn.lock

    - name: Install
      working-directory: ${{env.working-directory}}
      run: yarn install

    - name: Build
      working-directory: ${{env.working-directory}}
      run: yarn build
        
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: ${{env.working-directory}}/yarn.lock

    - name: Install
      working-directory: ${{env.working-directory}}
      run: yarn install

    - name: Test
      working-directory: ${{env.working-directory}}
      run: yarn test -- --watchAll=false
